# 使用Ubuntu基础镜像
FROM ubuntu:22.04

# 清除所有代理设置
ENV http_proxy=
ENV https_proxy=
ENV HTTP_PROXY=
ENV HTTPS_PROXY=
ENV no_proxy="localhost,127.0.0.1"
ENV NO_PROXY="localhost,127.0.0.1"

# 更新apt缓存
RUN apt-get update

# 设置工作目录
WORKDIR /app

# 运行命令保持容器运行
CMD ["bash"]